[tool.black]
target-version = ["py311"]
line-length = 120
include = '\.pyi?$'
exclude = '''
/(
    | __pycache__
    | .git
    | .mypy_cache
    | .pytest_cache
    | .tox
    | .venv
    | .vscode
    | node_modules
    | migrations
    | node_modules
)/
'''


# https://pycqa.github.io/isort/docs/configuration/options.html
[tool.isort]
atomic = true
line_length = 120
profile = "black"
combine_as_imports = true
default_section = "THIRDPARTY"
known_third_party = "django"
skip = [
    '.bzr', 
    '.direnv',
    '.eggs', 
    '.git',
    '.hg',
    '.mypy_cache',
    '.nox',
    '.pants.d',
    '.svn',
    '.tox', 
    '.venv', 
    '__pypackages__', 
    '_build',
    'buck-out',
    'build',
    'dist',
    'node_modules',
    'venv',
    'migrations',
]


[tool.mypy]
# python_version = 3.11
ignore_missing_imports = true

exclude = [
    '^.*?src/.*$',
    '^.*?/migrations/.*$',
    '^.*?/factories\.py$',
    "^.*?/?__pycache__/.*$",
    "^.git/.*$",
    "^.mypy_cache/.*$",
    "^.pytest_cache/.*$",
    "^.tox/.*$",
    "^.venv/.*$",
    "^.vscode/.*$",
    "^node_modules/.*$",
    '^.*?/tests/.*$',
]
