# Generated by Django 3.2.9 on 2021-11-12 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExampleModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moderation_date', models.DateTimeField(blank=True, null=True, verbose_name='Moderation Date')),
                ('moderation_state', models.IntegerField(choices=[(0, 'Not Moderated'), (1, 'Accepted'), (2, 'Rejected')], default=0, verbose_name='Moderation State')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
